/**
 * @fileoverview Dockerfile generator for pipeline packaging
 * @module sera-core/packaging/DockerfileGenerator
 *
 * Generates multi-stage Dockerfiles for packaged agent pipelines.
 * Supports node and python base images depending on runtime requirements.
 */

import type { PipelineSpec, DockerBuildConfig, DockerLayer } from '@sera/types';

/**
 * Analyze a pipeline spec to determine the appropriate base image.
 * Defaults to node:20-alpine unless a python-based runtime is detected.
 */
function selectBaseImage(spec: PipelineSpec): string {
    const runtimes = spec.nodes.map(n => n.config.runtime as string | undefined).filter(Boolean);
    if (runtimes.some(r => r === 'pydantic-ai' || r === 'python')) {
        return 'python:3.11-slim';
    }
    return 'node:20-alpine';
}

/**
 * Build a default DockerBuildConfig from a pipeline spec.
 */
export function buildDockerConfig(spec: PipelineSpec): DockerBuildConfig {
    const baseImage = selectBaseImage(spec);
    const isPython = baseImage.startsWith('python');

    const layers: DockerLayer[] = [];

    // System dependencies
    layers.push({
        comment: 'Install system dependencies',
        commands: isPython
            ? ['RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*']
            : ['RUN apk add --no-cache curl'],
    });

    // Application dependencies
    if (isPython) {
        layers.push({
            comment: 'Install Python dependencies',
            commands: [
                'COPY requirements.txt .',
                'RUN pip install --no-cache-dir -r requirements.txt',
            ],
        });
    } else {
        layers.push({
            comment: 'Install Node.js dependencies',
            commands: [
                'COPY package.json package-lock.json* ./',
                'RUN npm ci --production',
            ],
        });
    }

    // Pipeline spec and role files
    layers.push({
        comment: 'Copy pipeline spec and assets',
        commands: [
            'COPY pipeline.json .',
            'COPY roles/ roles/ 2>/dev/null || true',
            'COPY primers/ primers/ 2>/dev/null || true',
        ],
    });

    // Entrypoint script
    layers.push({
        comment: 'Copy entrypoint',
        commands: [
            'COPY entrypoint.js .',
        ],
    });

    // Environment variables from spec
    const environment: Record<string, string> = {};
    if (spec.variables) {
        for (const [key, def] of Object.entries(spec.variables)) {
            if (def.default !== undefined) {
                environment[`PIPELINE_VAR_${key.toUpperCase()}`] = String(def.default);
            }
        }
    }

    return {
        baseImage,
        layers,
        environment,
        volumes: ['/data'],
        entrypoint: isPython ? ['python', 'entrypoint.py'] : ['node', 'entrypoint.js'],
    };
}

/**
 * Generate a Dockerfile string from a DockerBuildConfig.
 */
export function generateDockerfile(config: DockerBuildConfig): string {
    const lines: string[] = [];

    lines.push(`# Auto-generated by sera-core packaging engine`);
    lines.push(`FROM ${config.baseImage}`);
    lines.push('');
    lines.push('WORKDIR /app');
    lines.push('');

    // Environment variables
    for (const [key, value] of Object.entries(config.environment)) {
        lines.push(`ENV ${key}=${JSON.stringify(value)}`);
    }
    if (Object.keys(config.environment).length > 0) {
        lines.push('');
    }

    // Layers
    for (const layer of config.layers) {
        lines.push(`# ${layer.comment}`);
        for (const cmd of layer.commands) {
            lines.push(cmd);
        }
        lines.push('');
    }

    // Volumes
    for (const vol of config.volumes) {
        lines.push(`VOLUME ${vol}`);
    }
    if (config.volumes.length > 0) {
        lines.push('');
    }

    // Entrypoint
    lines.push(`ENTRYPOINT ${JSON.stringify(config.entrypoint)}`);
    lines.push('');

    return lines.join('\n');
}

/**
 * Generate a Dockerfile directly from a pipeline spec.
 */
export function generateDockerfileFromSpec(spec: PipelineSpec): string {
    const config = buildDockerConfig(spec);
    return generateDockerfile(config);
}
