/**
 * @fileoverview PydanticAI pipeline compiler
 * @module sera-core/compiler/PydanticAICompiler
 *
 * Generates Python scripts using the stable PydanticAI Agent API.
 * Handles all 9 node types and 6 edge types by compiling to:
 * - pydantic_ai.Agent for LLM agent nodes
 * - asyncio.gather for parallel fork/join patterns
 * - Python if/else for condition nodes
 * - subprocess.run for deterministic-tool nodes
 * - Python functions for aggregator logic
 * - stdin/stdout for HITL interaction
 */

import type { PipelineSpec, PipelineNode, PipelineEdge } from '@sera/types';
import type { PipelineCompiler, CompilerResult } from './CompilerInterface';

/**
 * Topologically sort nodes using Kahn's algorithm.
 * Returns node IDs in execution order.
 */
function topologicalSort(nodes: PipelineNode[], edges: PipelineEdge[]): string[] {
    const inDegree = new Map<string, number>();
    const adjacency = new Map<string, string[]>();

    for (const node of nodes) {
        inDegree.set(node.id, 0);
        adjacency.set(node.id, []);
    }

    for (const edge of edges) {
        // Skip error edges for ordering - they're handled as exception paths
        if (edge.type === 'error') continue;
        const prev = inDegree.get(edge.target) ?? 0;
        inDegree.set(edge.target, prev + 1);
        adjacency.get(edge.source)?.push(edge.target);
    }

    const queue: string[] = [];
    for (const [id, deg] of inDegree) {
        if (deg === 0) queue.push(id);
    }

    const sorted: string[] = [];
    while (queue.length > 0) {
        const current = queue.shift()!;
        sorted.push(current);
        for (const neighbor of adjacency.get(current) ?? []) {
            const newDeg = (inDegree.get(neighbor) ?? 1) - 1;
            inDegree.set(neighbor, newDeg);
            if (newDeg === 0) queue.push(neighbor);
        }
    }

    return sorted;
}

/**
 * Detect parallel groups: sets of nodes that share the same fork source
 * via parallel-fork edges and converge via parallel-join edges.
 */
interface ParallelGroup {
    forkSourceId: string;
    branchIds: string[];
    joinTargetId: string | null;
}

function detectParallelGroups(edges: PipelineEdge[]): ParallelGroup[] {
    // Find fork sources: nodes with 2+ outgoing parallel-fork edges
    const forkEdges = edges.filter(e => e.type === 'parallel-fork');
    const forkSources = new Map<string, string[]>();
    for (const e of forkEdges) {
        const branches = forkSources.get(e.source) ?? [];
        branches.push(e.target);
        forkSources.set(e.source, branches);
    }

    const groups: ParallelGroup[] = [];
    for (const [sourceId, branchIds] of forkSources) {
        if (branchIds.length < 2) continue;

        // Find join target: node that all branches connect to via parallel-join edges
        const joinEdges = edges.filter(
            e => e.type === 'parallel-join' && branchIds.includes(e.source)
        );
        const joinTargets = new Map<string, number>();
        for (const e of joinEdges) {
            joinTargets.set(e.target, (joinTargets.get(e.target) ?? 0) + 1);
        }

        let joinTargetId: string | null = null;
        for (const [target, count] of joinTargets) {
            if (count >= 2) {
                joinTargetId = target;
                break;
            }
        }

        groups.push({ forkSourceId: sourceId, branchIds, joinTargetId });
    }

    return groups;
}

/**
 * Sanitize a node ID for use as a Python identifier.
 */
function pyId(nodeId: string): string {
    return nodeId.replace(/[^a-zA-Z0-9_]/g, '_');
}

/**
 * Escape a string for Python string literal (single-quoted).
 */
function pyStr(value: string): string {
    return value
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r');
}

/**
 * PydanticAI pipeline compiler.
 * Generates Python scripts using the stable Agent API.
 */
export class PydanticAICompiler implements PipelineCompiler {
    readonly framework = 'pydantic-ai';

    compile(spec: PipelineSpec, variables?: Record<string, unknown>): CompilerResult {
        const warnings: string[] = [];
        const lines: string[] = [];
        const nodeMap = new Map<string, PipelineNode>();
        for (const node of spec.nodes) {
            nodeMap.set(node.id, node);
        }

        const sorted = topologicalSort(spec.nodes, spec.edges);
        const parallelGroups = detectParallelGroups(spec.edges);

        // Track which nodes are branches in a parallel group (handled specially)
        const parallelBranchNodes = new Set<string>();
        const parallelJoinNodes = new Set<string>();
        for (const group of parallelGroups) {
            for (const id of group.branchIds) parallelBranchNodes.add(id);
            if (group.joinTargetId) parallelJoinNodes.add(group.joinTargetId);
        }

        // Header
        lines.push('#!/usr/bin/env python3');
        lines.push(`"""Auto-generated by sera-core compiler (framework: pydantic-ai)"""`);
        lines.push(`# Pipeline: ${pyStr(spec.name)} v${spec.version}`);
        lines.push('');

        // Imports
        lines.push('import asyncio');
        lines.push('import json');
        lines.push('import os');
        lines.push('import signal');
        lines.push('import subprocess');
        lines.push('import sys');
        lines.push('from pathlib import Path');
        lines.push('');
        lines.push('from pydantic_ai import Agent');
        lines.push('');

        // Event helper
        lines.push('def emit(event_type, node_id=None, data=None):');
        lines.push('    """Emit a structured event to stdout for sera-core to parse."""');
        lines.push('    evt = {"event": event_type}');
        lines.push('    if node_id: evt["nodeId"] = node_id');
        lines.push('    if data is not None: evt["data"] = data');
        lines.push('    print(json.dumps(evt), flush=True)');
        lines.push('');

        // Signal handlers for pause/resume/cancel
        lines.push('_paused = False');
        lines.push('_cancelled = False');
        lines.push('');
        lines.push('def _handle_pause(sig, frame):');
        lines.push('    global _paused');
        lines.push('    _paused = True');
        lines.push('    emit("pipeline:paused")');
        lines.push('');
        lines.push('def _handle_resume(sig, frame):');
        lines.push('    global _paused');
        lines.push('    _paused = False');
        lines.push('    emit("pipeline:resumed")');
        lines.push('');
        lines.push('def _handle_cancel(sig, frame):');
        lines.push('    global _cancelled');
        lines.push('    _cancelled = True');
        lines.push('    emit("pipeline:cancelled")');
        lines.push('    sys.exit(2)');
        lines.push('');
        lines.push('if hasattr(signal, "SIGUSR1"):');
        lines.push('    signal.signal(signal.SIGUSR1, _handle_pause)');
        lines.push('    signal.signal(signal.SIGUSR2, _handle_resume)');
        lines.push('signal.signal(signal.SIGTERM, _handle_cancel)');
        lines.push('');

        // Pause check helper
        lines.push('async def check_pause():');
        lines.push('    """Block while paused."""');
        lines.push('    while _paused:');
        lines.push('        await asyncio.sleep(0.5)');
        lines.push('');

        // Variables
        lines.push('# --- Pipeline Variables ---');
        lines.push('VARIABLES = {}');
        if (spec.variables) {
            for (const [key, def] of Object.entries(spec.variables)) {
                const resolved = variables?.[key] ?? def.default;
                const envKey = `PIPELINE_VAR_${key.toUpperCase()}`;
                lines.push(`VARIABLES['${pyStr(key)}'] = os.environ.get('${envKey}', ${JSON.stringify(resolved ?? '')})`);
            }
        }
        lines.push('');

        // Generate agent declarations for llm-agent nodes
        const agentNodes = spec.nodes.filter(n => n.type === 'llm-agent');
        if (agentNodes.length > 0) {
            lines.push('# --- Agents ---');
            for (const node of agentNodes) {
                const model = (node.config.model as string) || 'anthropic:claude-sonnet-4-5-20250929';
                const systemPrompt = (node.config.systemPrompt as string) || '';
                const roleFile = (node.config.roleFile as string) || '';

                const agentVar = `agent_${pyId(node.id)}`;

                if (roleFile) {
                    // Load system prompt from role file at runtime
                    lines.push(`_role_path_${pyId(node.id)} = Path(__file__).parent / 'roles' / '${pyStr(roleFile)}'`);
                    lines.push(`_system_prompt_${pyId(node.id)} = _role_path_${pyId(node.id)}.read_text() if _role_path_${pyId(node.id)}.exists() else '${pyStr(systemPrompt)}'`);
                    lines.push(`${agentVar} = Agent('${pyStr(model)}', system_prompt=_system_prompt_${pyId(node.id)})`);
                } else if (systemPrompt) {
                    lines.push(`${agentVar} = Agent('${pyStr(model)}', system_prompt='${pyStr(systemPrompt)}')`);
                } else {
                    lines.push(`${agentVar} = Agent('${pyStr(model)}')`);
                }
            }
            lines.push('');
        }

        // Generate node functions
        lines.push('# --- Node Functions ---');
        for (const node of spec.nodes) {
            this.generateNodeFunction(node, spec, lines, warnings);
            lines.push('');
        }

        // Generate main function
        lines.push('# --- Main ---');
        lines.push('async def main():');
        lines.push(`    emit('pipeline:started')`);
        lines.push('');

        this.generateMainBody(sorted, spec, parallelGroups, parallelBranchNodes, parallelJoinNodes, nodeMap, lines, warnings);

        lines.push('');
        lines.push(`    emit('pipeline:completed')`);
        lines.push('');
        lines.push('');
        lines.push("if __name__ == '__main__':");
        lines.push('    try:');
        lines.push('        asyncio.run(main())');
        lines.push('    except Exception as e:');
        lines.push("        emit('pipeline:failed', data={'error': str(e)})");
        lines.push('        sys.exit(1)');
        lines.push('');

        // Generate requirements.txt
        const requirements = [
            'pydantic-ai>=0.1.0',
        ];

        return {
            script: lines.join('\n'),
            scriptFilename: 'pipeline.py',
            files: [
                { name: 'requirements.txt', content: requirements.join('\n') + '\n' },
            ],
            warnings,
        };
    }

    /**
     * Generate an async function for a single node.
     */
    private generateNodeFunction(
        node: PipelineNode,
        spec: PipelineSpec,
        lines: string[],
        warnings: string[]
    ): void {
        const fnName = `node_${pyId(node.id)}`;

        switch (node.type) {
            case 'code-source':
                lines.push(`async def ${fnName}():`);
                lines.push(`    """code-source: ${pyStr(node.name)}"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    await check_pause()`);
                lines.push(`    # Read source files from workspace`);
                lines.push(`    workspace = os.environ.get('WORKSPACE_PATH', '.')`);
                lines.push(`    patterns = ${JSON.stringify((node.config.filePatterns as string[]) || ['**/*.sol'])}`);
                lines.push(`    files = []`);
                lines.push(`    for pattern in patterns:`);
                lines.push(`        for p in Path(workspace).glob(pattern):`);
                lines.push(`            if p.is_file():`);
                lines.push(`                try:`);
                lines.push(`                    files.append({'path': str(p.relative_to(workspace)), 'content': p.read_text()})`);
                lines.push(`                except Exception:`);
                lines.push(`                    pass`);
                lines.push(`    result = {'type': 'file-set', 'files': files}`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}')`);
                lines.push(`    return result`);
                break;

            case 'context-loader':
                lines.push(`async def ${fnName}(inputs):`);
                lines.push(`    """context-loader: ${pyStr(node.name)}"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    await check_pause()`);
                lines.push(`    workspace = os.environ.get('WORKSPACE_PATH', '.')`);
                lines.push(`    context_parts = []`);
                lines.push(`    if inputs and 'files' in inputs:`);
                lines.push(`        context_parts.append(json.dumps(inputs['files'][:5]))`);
                // Load configured context sources
                const sources = (node.config.sources as Array<{ type: string; path: string }>) || [];
                for (const source of sources) {
                    if (source.type === 'file' && source.path) {
                        lines.push(`    _ctx_path = Path(workspace) / '${pyStr(source.path)}'`);
                        lines.push(`    if _ctx_path.exists(): context_parts.append(_ctx_path.read_text())`);
                    } else if (source.type === 'primer' && source.path) {
                        lines.push(`    _primer_path = Path(__file__).parent / 'primers' / '${pyStr(source.path)}'`);
                        lines.push(`    if _primer_path.exists(): context_parts.append(_primer_path.read_text())`);
                    }
                }
                lines.push(`    result = {'type': 'context', 'content': '\\n---\\n'.join(context_parts)}`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}')`);
                lines.push(`    return result`);
                break;

            case 'llm-agent': {
                const agentVar = `agent_${pyId(node.id)}`;
                const timeout = (node.config.timeout as number) || 10800;
                lines.push(`async def ${fnName}(inputs):`);
                lines.push(`    """llm-agent: ${pyStr(node.name)}"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    await check_pause()`);
                lines.push(`    prompt = json.dumps(inputs) if isinstance(inputs, dict) else str(inputs)`);
                lines.push(`    result = await asyncio.wait_for(${agentVar}.run(prompt), timeout=${timeout})`);
                lines.push(`    output = {'type': 'agent-output', 'data': result.data}`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}')`);
                lines.push(`    return output`);
                break;
            }

            case 'deterministic-tool': {
                const toolName = (node.config.toolName as string) || 'unknown';
                const params = (node.config.parameters as Record<string, unknown>) || {};
                lines.push(`async def ${fnName}(inputs):`);
                lines.push(`    """deterministic-tool: ${pyStr(node.name)}"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    await check_pause()`);
                lines.push(`    cmd = ${JSON.stringify([toolName, ...Object.values(params).map(String)])}`);
                lines.push(`    try:`);
                lines.push(`        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)`);
                lines.push(`        try:`);
                lines.push(`            data = json.loads(proc.stdout)`);
                lines.push(`        except json.JSONDecodeError:`);
                lines.push(`            data = proc.stdout`);
                lines.push(`        output = {'type': 'tool-output', 'data': data, 'exitCode': proc.returncode}`);
                lines.push(`    except Exception as e:`);
                lines.push(`        output = {'type': 'tool-output', 'data': None, 'error': str(e)}`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}')`);
                lines.push(`    return output`);
                break;
            }

            case 'condition': {
                const expression = (node.config.expression as string) || 'True';
                lines.push(`async def ${fnName}(inputs):`);
                lines.push(`    """condition: ${pyStr(node.name)}"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    await check_pause()`);
                lines.push(`    variables = VARIABLES`);
                lines.push(`    try:`);
                lines.push(`        result = bool(eval('''${pyStr(expression)}''', {'inputs': inputs, 'variables': variables}))`);
                lines.push(`    except Exception:`);
                lines.push(`        result = False`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}', {'result': result})`);
                lines.push(`    return {'type': 'condition', 'result': result}`);
                break;
            }

            case 'aggregator': {
                const strategy = (node.config.strategy as string) || 'concat';
                lines.push(`async def ${fnName}(inputs_list):`);
                lines.push(`    """aggregator: ${pyStr(node.name)}"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    await check_pause()`);
                if (strategy === 'concat') {
                    lines.push(`    items = []`);
                    lines.push(`    for inp in inputs_list:`);
                    lines.push(`        if isinstance(inp, dict) and 'data' in inp:`);
                    lines.push(`            d = inp['data']`);
                    lines.push(`            if isinstance(d, list): items.extend(d)`);
                    lines.push(`            else: items.append(d)`);
                    lines.push(`        else: items.append(inp)`);
                } else if (strategy === 'deduplicate') {
                    const deduplicationKey = (node.config.deduplicationKey as string) || 'id';
                    lines.push(`    seen = set()`);
                    lines.push(`    items = []`);
                    lines.push(`    for inp in inputs_list:`);
                    lines.push(`        entries = inp.get('data', [inp]) if isinstance(inp, dict) else [inp]`);
                    lines.push(`        if not isinstance(entries, list): entries = [entries]`);
                    lines.push(`        for entry in entries:`);
                    lines.push(`            key = entry.get('${pyStr(deduplicationKey)}', str(entry)) if isinstance(entry, dict) else str(entry)`);
                    lines.push(`            if key not in seen:`);
                    lines.push(`                seen.add(key)`);
                    lines.push(`                items.append(entry)`);
                } else {
                    // Default: array strategy
                    lines.push(`    items = inputs_list`);
                }
                lines.push(`    result = {'type': 'aggregated', 'data': items}`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}')`);
                lines.push(`    return result`);
                break;
            }

            case 'sub-pipeline':
                warnings.push(`Sub-pipeline node '${node.name}' compiled as pass-through (nested compilation not yet supported)`);
                lines.push(`async def ${fnName}(inputs):`);
                lines.push(`    """sub-pipeline: ${pyStr(node.name)} (pass-through)"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    await check_pause()`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}')`);
                lines.push(`    return inputs`);
                break;

            case 'human-in-the-loop': {
                const prompt = (node.config.prompt as string) || 'Approve?';
                const timeoutMinutes = (node.config.timeoutMinutes as number) || 60;
                lines.push(`async def ${fnName}(inputs):`);
                lines.push(`    """human-in-the-loop: ${pyStr(node.name)}"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    emit('hitl:waiting', '${pyStr(node.id)}', {'prompt': '${pyStr(prompt)}', 'inputs': inputs})`);
                lines.push(`    # Wait for approval via stdin or timeout`);
                lines.push(`    import select`);
                lines.push(`    timeout_s = ${timeoutMinutes} * 60`);
                lines.push(`    print(json.dumps({'event': 'hitl:prompt', 'prompt': '${pyStr(prompt)}'}), flush=True)`);
                lines.push(`    # In automated mode, auto-approve`);
                lines.push(`    auto_approve = os.environ.get('HITL_AUTO_APPROVE', '').lower() in ('1', 'true', 'yes')`);
                lines.push(`    if auto_approve:`);
                lines.push(`        approved = True`);
                lines.push(`    else:`);
                lines.push(`        try:`);
                lines.push(`            ready, _, _ = select.select([sys.stdin], [], [], timeout_s)`);
                lines.push(`            if ready:`);
                lines.push(`                response = sys.stdin.readline().strip().lower()`);
                lines.push(`                approved = response in ('y', 'yes', 'approve', '1', 'true')`);
                lines.push(`            else:`);
                lines.push(`                emit('hitl:timeout', '${pyStr(node.id)}')`);
                lines.push(`                approved = False`);
                lines.push(`        except Exception:`);
                lines.push(`            approved = False`);
                lines.push(`    event_type = 'hitl:approved' if approved else 'hitl:rejected'`);
                lines.push(`    emit(event_type, '${pyStr(node.id)}')`);
                lines.push(`    if not approved:`);
                lines.push(`        raise RuntimeError('HITL approval rejected or timed out')`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}')`);
                lines.push(`    return inputs`);
                break;
            }

            case 'output-format': {
                const format = (node.config.format as string) || 'json';
                lines.push(`async def ${fnName}(inputs):`);
                lines.push(`    """output-format: ${pyStr(node.name)}"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    await check_pause()`);
                if (format === 'json') {
                    lines.push(`    output = json.dumps(inputs, indent=2, default=str)`);
                } else if (format === 'markdown' || format === 'text') {
                    const template = (node.config.template as string) || '';
                    if (template) {
                        lines.push(`    output = '${pyStr(template)}'`);
                    } else {
                        lines.push(`    output = str(inputs)`);
                    }
                } else {
                    // notepad-issues or other formats
                    lines.push(`    output = json.dumps(inputs, default=str)`);
                }
                lines.push(`    output_path = os.environ.get('OUTPUT_PATH')`);
                lines.push(`    if output_path:`);
                lines.push(`        Path(output_path).write_text(output)`);
                lines.push(`    result = {'type': 'formatted', 'format': '${pyStr(format)}', 'content': output}`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}', result)`);
                lines.push(`    return result`);
                break;
            }

            default:
                warnings.push(`Unknown node type '${node.type}' for node '${node.name}' - compiled as pass-through`);
                lines.push(`async def ${fnName}(inputs=None):`);
                lines.push(`    """${node.type}: ${pyStr(node.name)} (pass-through)"""`);
                lines.push(`    emit('node:started', '${pyStr(node.id)}')`);
                lines.push(`    emit('node:completed', '${pyStr(node.id)}')`);
                lines.push(`    return inputs`);
        }
    }

    /**
     * Generate the main() function body with correct execution ordering.
     */
    private generateMainBody(
        sorted: string[],
        spec: PipelineSpec,
        parallelGroups: ParallelGroup[],
        parallelBranchNodes: Set<string>,
        parallelJoinNodes: Set<string>,
        nodeMap: Map<string, PipelineNode>,
        lines: string[],
        _warnings: string[]
    ): void {
        // Track which nodes have been emitted
        const emitted = new Set<string>();
        // Track result variables
        const resultVars = new Map<string, string>();
        let varCounter = 0;

        for (const nodeId of sorted) {
            if (emitted.has(nodeId)) continue;

            const node = nodeMap.get(nodeId);
            if (!node) continue;

            // Check if this node is a fork source for a parallel group
            const group = parallelGroups.find(g => g.forkSourceId === nodeId);
            if (group) {
                // Emit the fork source node first
                const sourceVar = `r${varCounter++}`;
                resultVars.set(nodeId, sourceVar);
                const fnName = `node_${pyId(nodeId)}`;
                const inputExpr = this.getInputExpression(nodeId, spec.edges, resultVars);
                lines.push(`    ${sourceVar} = await ${fnName}(${inputExpr})`);
                emitted.add(nodeId);

                // Emit parallel branches using asyncio.gather
                const branchVars: string[] = [];
                for (const branchId of group.branchIds) {
                    branchVars.push(`r${varCounter}`);
                    resultVars.set(branchId, `r${varCounter}`);
                    varCounter++;
                }
                const branchCalls = group.branchIds.map(id => {
                    const fn = `node_${pyId(id)}`;
                    return `${fn}(${sourceVar})`;
                });
                lines.push(`    ${branchVars.join(', ')} = await asyncio.gather(${branchCalls.join(', ')})`);
                for (const id of group.branchIds) emitted.add(id);

                // Emit join target if it exists
                if (group.joinTargetId) {
                    const joinVar = `r${varCounter++}`;
                    resultVars.set(group.joinTargetId, joinVar);
                    const joinFn = `node_${pyId(group.joinTargetId)}`;
                    lines.push(`    ${joinVar} = await ${joinFn}([${branchVars.join(', ')}])`);
                    emitted.add(group.joinTargetId);
                }

                continue;
            }

            // Skip nodes already handled as parallel branches or join targets
            if (parallelBranchNodes.has(nodeId) || parallelJoinNodes.has(nodeId)) continue;

            const resultVar = `r${varCounter++}`;
            resultVars.set(nodeId, resultVar);
            const fnName = `node_${pyId(nodeId)}`;

            // Handle condition nodes - generate if/else branching
            if (node.type === 'condition') {
                const inputExpr = this.getInputExpression(nodeId, spec.edges, resultVars);
                lines.push(`    ${resultVar} = await ${fnName}(${inputExpr})`);
                emitted.add(nodeId);

                // Find conditional edges and their targets
                const conditionalEdges = spec.edges.filter(
                    e => e.source === nodeId && e.type === 'conditional'
                );
                if (conditionalEdges.length >= 2) {
                    const trueEdge = conditionalEdges[0];
                    const falseEdge = conditionalEdges[1];
                    const trueBranch = `r${varCounter++}`;
                    const falseBranch = `r${varCounter++}`;

                    resultVars.set(trueEdge.target, trueBranch);
                    resultVars.set(falseEdge.target, falseBranch);

                    const trueFn = `node_${pyId(trueEdge.target)}`;
                    const falseFn = `node_${pyId(falseEdge.target)}`;

                    lines.push(`    if ${resultVar}['result']:`);
                    lines.push(`        ${trueBranch} = await ${trueFn}(${this.getInputExpression(trueEdge.target, spec.edges, resultVars, nodeId)})`);
                    lines.push(`    else:`);
                    lines.push(`        ${falseBranch} = await ${falseFn}(${this.getInputExpression(falseEdge.target, spec.edges, resultVars, nodeId)})`);

                    emitted.add(trueEdge.target);
                    emitted.add(falseEdge.target);
                }

                continue;
            }

            // Normal sequential node
            const inputExpr = this.getInputExpression(nodeId, spec.edges, resultVars);
            if (node.type === 'code-source' && !inputExpr) {
                lines.push(`    ${resultVar} = await ${fnName}()`);
            } else {
                lines.push(`    ${resultVar} = await ${fnName}(${inputExpr})`);
            }
            emitted.add(nodeId);
        }
    }

    /**
     * Determine the input expression for a node based on incoming edges.
     */
    private getInputExpression(
        nodeId: string,
        edges: PipelineEdge[],
        resultVars: Map<string, string>,
        skipSource?: string
    ): string {
        const incomingEdges = edges.filter(
            e => e.target === nodeId && e.type !== 'error' && e.source !== skipSource
        );

        if (incomingEdges.length === 0) return '';
        if (incomingEdges.length === 1) {
            return resultVars.get(incomingEdges[0].source) ?? 'None';
        }

        // Multiple inputs - pass as list
        const vars = incomingEdges
            .map(e => resultVars.get(e.source))
            .filter(Boolean);
        return `[${vars.join(', ')}]`;
    }
}
